name: clang-format-8_windows-amd64

on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: get llvm-project
      run: |
        choco install wget
        wget https://github.com/llvm/llvm-project/releases/download/llvmorg-8.0.1/llvm-8.0.1.src.tar.xz
        wget https://github.com/llvm/llvm-project/releases/download/llvmorg-8.0.1/cfe-8.0.1.src.tar.xz
        wget https://github.com/llvm/llvm-project/releases/download/llvmorg-8.0.1/clang-tools-extra-8.0.1.src.tar.xz
        $env:Path = "C:\Program Files\Git\usr\bin;$env:Path"
        tar.exe xf llvm-8.0.1.src.tar.xz
        tar.exe xf cfe-8.0.1.src.tar.xz --exclude=cfe-8.0.1.src/test/Driver/Inputs*
        tar.exe xf clang-tools-extra-8.0.1.src.tar.xz
        mkdir llvm-project-8.0.1
        mv llvm-8.0.1.src llvm-project-8.0.1/llvm
        mv cfe-8.0.1.src llvm-project-8.0.1/clang
        mv clang-tools-extra-8.0.1.src llvm-project-8.0.1/clang-tools-extra
        Get-Content windows-clang-8-include-string.patch | patch.exe llvm-project-8.0.1/llvm/include/llvm/Demangle/MicrosoftDemangleNodes.h
    - name: make build directory
      run: mkdir -p llvm-project-8.0.1/build
    - name: cmake
      run: cd llvm-project-8.0.1/build && cmake ../llvm -Thost=x64 -DLLVM_ENABLE_PROJECTS="clang;clang-tools-extra" -DBUILD_SHARED_LIBS=OFF -DCMAKE_CXX_FLAGS="/MP" -DLLVM_USE_CRT_MINSIZEREL="MT"
    - name: build
      run: cd llvm-project-8.0.1/build && cmake --build . --config MinSizeRel --target clang-format clang-query clang-tidy
    - name: rename output binary
      run: |
        mv llvm-project-8.0.1\build\MinSizeRel\bin\clang-format.exe llvm-project-8.0.1\build\MinSizeRel\bin\clang-format-8_windows-amd64.exe
        mv llvm-project-8.0.1\build\MinSizeRel\bin\clang-query.exe llvm-project-8.0.1\build\MinSizeRel\bin\clang-query-8_windows-amd64.exe
        mv llvm-project-8.0.1\build\MinSizeRel\bin\clang-tidy.exe llvm-project-8.0.1\build\MinSizeRel\bin\clang-tidy-8_windows-amd64.exe
    - name: create and print sha512sum
      run: |
        $env:Path = "C:\Program Files\Git\usr\bin;$env:Path"
        cd llvm-project-8.0.1\build\MinSizeRel\bin
        sha512sum.exe clang-format-8_windows-amd64.exe > clang-format-8_windows-amd64.exe.sha512sum
        sha512sum.exe clang-query-8_windows-amd64.exe > clang-query-8_windows-amd64.exe.sha512sum
        sha512sum.exe clang-tidy-8_windows-amd64.exe > clang-tidy-8_windows-amd64.exe.sha512sum
        echo "Checksums are: "
        Get-Content -Path clang-format-8_windows-amd64.exe.sha512sum
        Get-Content -Path clang-query-8_windows-amd64.exe.sha512sum
        Get-Content -Path clang-tidy-8_windows-amd64.exe.sha512sum
    - name: upload release
      uses: xresloader/upload-to-github-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        file: "llvm-project-8.0.1/build/MinSizeRel/bin/clang-*-8_windows-amd64.exe*"
        draft: true
