name: clang-format-9_windows-amd64

on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: get llvm-project
      run: |
        choco install wget
        wget https://github.com/llvm/llvm-project/releases/download/llvmorg-9.0.1/llvm-project-9.0.1.tar.xz
        $env:Path = "C:\Program Files\Git\usr\bin;$env:Path"
        tar xf llvm-project-9.0.1.tar.xz --exclude=llvm-project-9.0.1/clang/test/Driver/Inputs* --exclude=llvm-project-9.0.1/libclc/amdgcn-mesa3d --exclude=llvm-project-9.0.1/libcxx/test/std/input.output/filesystems/Inputs/static_test_env/*
        Get-Content windows-clang-9-10-trivially-copyable-mismatch.patch | patch.exe llvm-project-9.0.1/llvm/cmake/config-ix.cmake
    - name: make build directory
      run: mkdir -p llvm-project-9.0.1/build
    - name: cmake
      run: cd llvm-project-9.0.1/build && cmake ../llvm -Thost=x64 -DLLVM_ENABLE_PROJECTS="clang;clang-tools-extra" -DBUILD_SHARED_LIBS=OFF -DCMAKE_CXX_FLAGS="/MP /std:c++14" -DLLVM_USE_CRT_MINSIZEREL="MT"
    - name: build
      run: cd llvm-project-9.0.1/build && cmake --build . --config MinSizeRel --target clang-format clang-query clang-tidy
    - name: rename output binary
      run: |
        mv llvm-project-9.0.1\build\MinSizeRel\bin\clang-format.exe llvm-project-9.0.1\build\MinSizeRel\bin\clang-format-9_windows-amd64.exe
        mv llvm-project-9.0.1\build\MinSizeRel\bin\clang-query.exe llvm-project-9.0.1\build\MinSizeRel\bin\clang-query-9_windows-amd64.exe
        mv llvm-project-9.0.1\build\MinSizeRel\bin\clang-tidy.exe llvm-project-9.0.1\build\MinSizeRel\bin\clang-tidy-9_windows-amd64.exe
    - name: create and print sha512sum
      run: |
        $env:Path = "C:\Program Files\Git\usr\bin;$env:Path"
        cd llvm-project-9.0.1\build\MinSizeRel\bin
        sha512sum.exe clang-format-9_windows-amd64.exe > clang-format-9_windows-amd64.exe.sha512sum
        sha512sum.exe clang-query-9_windows-amd64.exe > clang-query-9_windows-amd64.exe.sha512sum
        sha512sum.exe clang-tidy-9_windows-amd64.exe > clang-tidy-9_windows-amd64.exe.sha512sum
        echo "Checksums are: "
        Get-Content -Path clang-format-9_windows-amd64.exe.sha512sum
        Get-Content -Path clang-query-9_windows-amd64.exe.sha512sum
        Get-Content -Path clang-tidy-9_windows-amd64.exe.sha512sum
    - name: upload release
      uses: xresloader/upload-to-github-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        file: "llvm-project-9.0.1/build/MinSizeRel/bin/clang-*-9_windows-amd64.exe*"
        draft: true
