name: clang-tools-8_linux-amd64

on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: get llvm-project
      run: |
        wget https://github.com/llvm/llvm-project/releases/download/llvmorg-8.0.1/llvm-8.0.1.src.tar.xz
        wget https://github.com/llvm/llvm-project/releases/download/llvmorg-8.0.1/cfe-8.0.1.src.tar.xz
        wget https://github.com/llvm/llvm-project/releases/download/llvmorg-8.0.1/clang-tools-extra-8.0.1.src.tar.xz
        tar xf llvm-8.0.1.src.tar.xz
        tar xf cfe-8.0.1.src.tar.xz
        tar xf clang-tools-extra-8.0.1.src.tar.xz
        mkdir llvm-project-8.0.1
        mv llvm-8.0.1.src llvm-project-8.0.1/llvm
        mv cfe-8.0.1.src llvm-project-8.0.1/clang
        mv clang-tools-extra-8.0.1.src llvm-project-8.0.1/clang-tools-extra
        patch llvm-project-8.0.1/llvm/include/llvm/Demangle/MicrosoftDemangleNodes.h include-cstdint-string-prior-to-using-uint8_t.patch
    - name: make build directory
      run: mkdir -p llvm-project-8.0.1/build
    - name: cmake
      run: cd llvm-project-8.0.1/build && cmake ../llvm -DLLVM_ENABLE_PROJECTS="clang;clang-tools-extra" -DBUILD_SHARED_LIBS=OFF -DCMAKE_BUILD_TYPE=MinSizeRel -DLLVM_BUILD_STATIC=ON -DCLANG_ANALYZER_ENABLE_Z3_SOLVER=OFF -DCMAKE_CXX_FLAGS="-s -flto" -DCMAKE_CXX_COMPILER=g++-10 -DCMAKE_C_COMPILER=gcc-10
    - name: build
      run: cd llvm-project-8.0.1/build && make clang-format clang-query clang-tidy -j$(nproc)
    - name: rename output binary
      run: |
        cd llvm-project-8.0.1/build/bin
        mv clang-format clang-format-8_linux-amd64
        mv clang-query clang-query-8_linux-amd64
        mv clang-tidy clang-tidy-8_linux-amd64
    - name: create and print sha512sum
      run: |
        cd llvm-project-8.0.1/build/bin
        sha512sum clang-format-8_linux-amd64 > clang-format-8_linux-amd64.sha512sum
        sha512sum clang-query-8_linux-amd64 > clang-query-8_linux-amd64.sha512sum
        sha512sum clang-tidy-8_linux-amd64 > clang-tidy-8_linux-amd64.sha512sum
        echo "Checksums are: "
        cat clang-format-8_linux-amd64.sha512sum
        cat clang-query-8_linux-amd64.sha512sum
        cat clang-tidy-8_linux-amd64.sha512sum
    - name: upload release
      uses: xresloader/upload-to-github-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        file: "llvm-project-8.0.1/build/bin/clang-*-8_linux-amd64*"
        draft: true
